In [3]:
#https://code.google.com/p/bigquery-e2e/source/browse/samples/ch06/run_load.py
from apiclient.http import MediaFileUpload
import time
import json
import datetime

import auth
import run_load

In [4]:
service = auth.build_bq_client()

In [5]:
# Delete a table
def deleteTable(projectId, datasetId, tableId):
    service.tables().delete(projectId=projectId, datasetId=datasetId, tableId=tableId).execute()

In [6]:
def loadTable(projectId,datasetId, load_file, table):

    # Load configuration with the destination specified.
    load_config = {
      'destinationTable': {
        'projectId': projectId,
        'datasetId': datasetId,
        # You can update this for each example.
        'tableId': table
      }
    }
    # Setup the job here.
    # load[property] = value
    load_config['schema'] = {
      'fields': [
        {'name':'id', 'type':'integer'},
        {'name':'tc_id', 'type':'integer'},
        {'name':'trip_id', 'type':'string'},
        {'name':'main_leg', 'type':'integer'},
        {'name':'trip_link', 'type':'string'},
        {'name':'driver_id', 'type':'integer'},
        {'name':'trip_created_at', 'type':'timestamp'},
        {'name':'trip_departure_datetime', 'type':'timestamp'},
        {'name':'departure_address', 'type':'string'},
        {'name':'destination_address', 'type':'string'},
        {'name':'departure_city', 'type':'string'},
        {'name':'destination_city', 'type':'string'},
        {'name':'departure_state', 'type':'string'},
        {'name':'destination_state', 'type':'string'},
        {'name':'departure_country', 'type':'string'},
        {'name':'destination_country', 'type':'string'},
        {'name':'country', 'type':'string'},
        {'name':'seats_offered', 'type':'integer'},
        {'name':'trip_distance', 'type':'float'},
        {'name':'suggested_price', 'type':'integer'},
        {'name':'price', 'type':'integer'},
        {'name':'trip_canceled', 'type':'integer'},
        {'name':'auto_accept', 'type':'integer'},
        {'name':'trip_comment', 'type':'integer'},
        {'name':'driver_message', 'type':'integer'},
        {'name':'pax_message', 'type':'integer'},
        {'name':'recurrent', 'type':'integer'},
        {'name':'ladies_only', 'type':'integer'},
        {'name':'is_return', 'type':'integer'},
        {'name':'seats_booked', 'type':'integer'},
        {'name':'seats_approved', 'type':'integer'},
        {'name':'seats_canceled', 'type':'integer'},
        {'name':'seats_rejected', 'type':'integer'},
        {'name':'promo_code', 'type':'string'},
        {'name':'description_code', 'type':'string'}
      ]
    }

    upload = MediaFileUpload(load_file, mimetype='application/octet-stream', resumable=True)
    # End of job configuration
    run_load.start_and_wait(service.jobs(),
                            'kinetic-valor-110522',
                            load_config,
                            media_body=upload)

In [28]:
def main():
    inicio = datetime.datetime.now() 
    deleteTable('kinetic-valor-110522', 'dataset', 'trips')
    loadTable('kinetic-valor-110522','dataset', 'trips6.csv','trips')
    print datetime.datetime.now() - inicio

In [29]:
if __name__ == '__main__':
    main()

{
  "status": {
    "state": "PENDING"
  },
  "kind": "bigquery#job",
  "statistics": {
    "creationTime": "1448910750506"
  },
  "jobReference": {
    "projectId": "kinetic-valor-110522",
    "jobId": "ch06_1448910794"
  },
  "etag": "\"Bop49sEVg6UBKwr7tLdL8AavHaw/eakyONZl_pjdjUwRQ2hkI0Qbkxg\"",
  "user_email": "ricardo.nakano@tripda.com.br",
  "configuration": {
    "load": {
      "destinationTable": {
        "projectId": "kinetic-valor-110522",
        "tableId": "trips",
        "datasetId": "dataset"
      },
      "schema": {
        "fields": [
          {
            "type": "INTEGER",
            "name": "id"
          },
          {
            "type": "INTEGER",
            "name": "tc_id"
          },
          {
            "type": "STRING",
            "name": "trip_id"
          },
          {
            "type": "INTEGER",
            "name": "main_leg"
          },
          {
            "type": "STRING",
            "name": "trip_link"
          },
          {
            "type": "INTEGER",
            "name": "driver_id"
          },
          {
            "type": "TIMESTAMP",
            "name": "trip_created_at"
          },
          {
            "type": "TIMESTAMP",
            "name": "trip_departure_datetime"
          },
          {
            "type": "STRING",
            "name": "departure_address"
          },
          {
            "type": "STRING",
            "name": "destination_address"
          },
          {
            "type": "STRING",
            "name": "departure_city"
          },
          {
            "type": "STRING",
            "name": "destination_city"
          },
          {
            "type": "STRING",
            "name": "departure_state"
          },
          {
            "type": "STRING",
            "name": "destination_state"
          },
          {
            "type": "STRING",
            "name": "departure_country"
          },
          {
            "type": "STRING",
            "name": "destination_country"
          },
          {
            "type": "STRING",
            "name": "country"
          },
          {
            "type": "INTEGER",
            "name": "seats_offered"
          },
          {
            "type": "FLOAT",
            "name": "trip_distance"
          },
          {
            "type": "INTEGER",
            "name": "suggested_price"
          },
          {
            "type": "INTEGER",
            "name": "price"
          },
          {
            "type": "INTEGER",
            "name": "trip_canceled"
          },
          {
            "type": "INTEGER",
            "name": "auto_accept"
          },
          {
            "type": "INTEGER",
            "name": "trip_comment"
          },
          {
            "type": "INTEGER",
            "name": "driver_message"
          },
          {
            "type": "INTEGER",
            "name": "pax_message"
          },
          {
            "type": "INTEGER",
            "name": "recurrent"
          },
          {
            "type": "INTEGER",
            "name": "ladies_only"
          },
          {
            "type": "INTEGER",
            "name": "is_return"
          },
          {
            "type": "INTEGER",
            "name": "seats_booked"
          },
          {
            "type": "INTEGER",
            "name": "seats_approved"
          },
          {
            "type": "INTEGER",
            "name": "seats_canceled"
          },
          {
            "type": "INTEGER",
            "name": "seats_rejected"
          },
          {
            "type": "STRING",
            "name": "promo_code"
          },
          {
            "type": "STRING",
            "name": "description_code"
          }
        ]
      }
    }
  },
  "id": "kinetic-valor-110522:ch06_1448910794",
  "selfLink": "https://www.googleapis.com/bigquery/v2/projects/kinetic-valor-110522/jobs/ch06_1448910794"
}
PENDING 27s
PENDING 37s
RUNNING 48s
DONE 58s
SUCCESS
0:00:58.858182

In [ ]:
0:12:30.201387
0:13:45.329555
0:11:22.807578
0:11:27.131818
0:10:50.352576
0:14:53.831387
0:10:13.743573
0:10:17.838532


0:07:11.612308
0:04:22.202682
0:02:23.298047
0:01:57.056721
0:01:00.911497
0:00:58.858182

In [6]:
initial_date = datetime.date(2015, 05, 01)
current_date = datetime.datetime.now().date()



day = datetime.timedelta(days=1)

while initial_date <= current_date:
    print initial_date
    initial_date += day

2015-05-01
2015-05-02
2015-05-03
2015-05-04
2015-05-05
2015-05-06
2015-05-07
2015-05-08
2015-05-09
2015-05-10
2015-05-11
2015-05-12
2015-05-13
2015-05-14
2015-05-15
2015-05-16
2015-05-17
2015-05-18
2015-05-19
2015-05-20
2015-05-21
2015-05-22
2015-05-23
2015-05-24
2015-05-25
2015-05-26
2015-05-27
2015-05-28
2015-05-29
2015-05-30
2015-05-31
2015-06-01
2015-06-02
2015-06-03
2015-06-04
2015-06-05
2015-06-06
2015-06-07
2015-06-08
2015-06-09
2015-06-10
2015-06-11
2015-06-12
2015-06-13
2015-06-14
2015-06-15
2015-06-16
2015-06-17
2015-06-18
2015-06-19
2015-06-20
2015-06-21
2015-06-22
2015-06-23
2015-06-24
2015-06-25
2015-06-26
2015-06-27
2015-06-28
2015-06-29
2015-06-30
2015-07-01
2015-07-02
2015-07-03
2015-07-04
2015-07-05
2015-07-06
2015-07-07
2015-07-08
2015-07-09
2015-07-10
2015-07-11
2015-07-12
2015-07-13
2015-07-14
2015-07-15
2015-07-16
2015-07-17
2015-07-18
2015-07-19
2015-07-20
2015-07-21
2015-07-22
2015-07-23
2015-07-24
2015-07-25
2015-07-26
2015-07-27
2015-07-28
2015-07-29
2015-07-30
2015-07-31
2015-08-01
2015-08-02
2015-08-03
2015-08-04
2015-08-05
2015-08-06
2015-08-07
2015-08-08
2015-08-09
2015-08-10
2015-08-11
2015-08-12
2015-08-13
2015-08-14
2015-08-15
2015-08-16
2015-08-17
2015-08-18
2015-08-19
2015-08-20
2015-08-21
2015-08-22
2015-08-23
2015-08-24
2015-08-25
2015-08-26
2015-08-27
2015-08-28
2015-08-29
2015-08-30
2015-08-31
2015-09-01
2015-09-02
2015-09-03
2015-09-04
2015-09-05
2015-09-06
2015-09-07
2015-09-08
2015-09-09
2015-09-10
2015-09-11
2015-09-12
2015-09-13
2015-09-14
2015-09-15
2015-09-16
2015-09-17
2015-09-18
2015-09-19
2015-09-20
2015-09-21
2015-09-22
2015-09-23
2015-09-24
2015-09-25
2015-09-26
2015-09-27
2015-09-28
2015-09-29
2015-09-30
2015-10-01
2015-10-02
2015-10-03
2015-10-04
2015-10-05
2015-10-06
2015-10-07
2015-10-08
2015-10-09
2015-10-10
2015-10-11
2015-10-12
2015-10-13
2015-10-14
2015-10-15
2015-10-16
2015-10-17
2015-10-18
2015-10-19
2015-10-20
2015-10-21
2015-10-22
2015-10-23
2015-10-24
2015-10-25
2015-10-26
2015-10-27
2015-10-28
2015-10-29
2015-10-30
2015-10-31
2015-11-01
2015-11-02
2015-11-03
2015-11-04
2015-11-05
2015-11-06
2015-11-07
2015-11-08
2015-11-09
2015-11-10
2015-11-11
2015-11-12
2015-11-13
2015-11-14
2015-11-15
2015-11-16
2015-11-17
2015-11-18
2015-11-19
2015-11-20
2015-11-21
2015-11-22
2015-11-23
2015-11-24
2015-11-25

In [21]:
loadTable('kinetic-valor-110522','dataset', 'trips4.csv','trips')

{
  "status": {
    "state": "PENDING"
  },
  "kind": "bigquery#job",
  "statistics": {
    "creationTime": "1448907838254"
  },
  "jobReference": {
    "projectId": "kinetic-valor-110522",
    "jobId": "ch06_1448907824"
  },
  "etag": "\"Bop49sEVg6UBKwr7tLdL8AavHaw/ULYGWPNr0Flbomm0-ZdLJB-JCuY\"",
  "user_email": "ricardo.nakano@tripda.com.br",
  "configuration": {
    "load": {
      "destinationTable": {
        "projectId": "kinetic-valor-110522",
        "tableId": "trips",
        "datasetId": "dataset"
      },
      "schema": {
        "fields": [
          {
            "type": "INTEGER",
            "name": "id"
          },
          {
            "type": "INTEGER",
            "name": "tc_id"
          },
          {
            "type": "STRING",
            "name": "trip_id"
          },
          {
            "type": "INTEGER",
            "name": "main_leg"
          },
          {
            "type": "STRING",
            "name": "trip_link"
          },
          {
            "type": "INTEGER",
            "name": "driver_id"
          },
          {
            "type": "TIMESTAMP",
            "name": "trip_created_at"
          },
          {
            "type": "TIMESTAMP",
            "name": "trip_departure_datetime"
          },
          {
            "type": "STRING",
            "name": "departure_address"
          },
          {
            "type": "STRING",
            "name": "destination_address"
          },
          {
            "type": "STRING",
            "name": "departure_city"
          },
          {
            "type": "STRING",
            "name": "destination_city"
          },
          {
            "type": "STRING",
            "name": "departure_state"
          },
          {
            "type": "STRING",
            "name": "destination_state"
          },
          {
            "type": "STRING",
            "name": "departure_country"
          },
          {
            "type": "STRING",
            "name": "destination_country"
          },
          {
            "type": "STRING",
            "name": "country"
          },
          {
            "type": "INTEGER",
            "name": "seats_offered"
          },
          {
            "type": "FLOAT",
            "name": "trip_distance"
          },
          {
            "type": "INTEGER",
            "name": "suggested_price"
          },
          {
            "type": "INTEGER",
            "name": "price"
          },
          {
            "type": "INTEGER",
            "name": "trip_canceled"
          },
          {
            "type": "INTEGER",
            "name": "auto_accept"
          },
          {
            "type": "INTEGER",
            "name": "trip_comment"
          },
          {
            "type": "INTEGER",
            "name": "driver_message"
          },
          {
            "type": "INTEGER",
            "name": "pax_message"
          },
          {
            "type": "INTEGER",
            "name": "recurrent"
          },
          {
            "type": "INTEGER",
            "name": "ladies_only"
          },
          {
            "type": "INTEGER",
            "name": "is_return"
          },
          {
            "type": "INTEGER",
            "name": "seats_booked"
          },
          {
            "type": "INTEGER",
            "name": "seats_approved"
          },
          {
            "type": "INTEGER",
            "name": "seats_canceled"
          },
          {
            "type": "INTEGER",
            "name": "seats_rejected"
          },
          {
            "type": "STRING",
            "name": "promo_code"
          },
          {
            "type": "STRING",
            "name": "description_code"
          }
        ]
      }
    }
  },
  "id": "kinetic-valor-110522:ch06_1448907824",
  "selfLink": "https://www.googleapis.com/bigquery/v2/projects/kinetic-valor-110522/jobs/ch06_1448907824"
}
PENDING 85s
PENDING 95s
PENDING 106s
PENDING 116s
RUNNING 126s
RUNNING 136s
RUNNING 147s
RUNNING 157s
RUNNING 168s
RUNNING 178s
RUNNING 188s
RUNNING 198s
RUNNING 209s
RUNNING 219s
RUNNING 229s
DONE 239s
SUCCESS

In [84]:
def loadTableTeste(projectId,datasetId, load_file, table):

    # Load configuration with the destination specified.
    load_config = {
      'destinationTable': {
        'projectId': projectId,
        'datasetId': datasetId,
        # You can update this for each example.
        'tableId': table
      }
    }
    # Setup the job here.
    # load[property] = value
    load_config['schema'] = {
      'fields': [
        {'name':'id', 'type':'integer'},
        {'name':'tc_id', 'type':'string'},
        {"name":"coord", "type":"RECORD"},
        [
          {"name":"lon", "type":"FLOAT"},
          {"name":"lat", "type":"FLOAT"}
        ],
      ]
    }

    upload = MediaFileUpload(load_file, mimetype='application/octet-stream', resumable=True)
    # End of job configuration
    run_load.start_and_wait(service.jobs(),
                            'kinetic-valor-110522',
                            load_config,
                            media_body=upload)

In [87]:
loadTableTeste('kinetic-valor-110522','dataset', 'sample.csv','teste')

ResumableUploadError: <HttpError 400 "Field coord is type RECORD but has no schema">

In [ ]:
deleteTable('kinetic-valor-110522', 'dataset', 'teste')

In [86]:
import pandas as pd

headers = ['id','tc_id','coord']
df = pd.DataFrame(columns=headers)

row1 = ['1', 'True', "{lon:2.3, lat:4.5}"]
row2 = ['2', 'True', "{lon:2.3, lat:4.5}"]
row3 = ['3', 'True', "{lon:2.3, lat:4.5}"]
#row4 = ['4', 'False', {"lon":"2.6", "lat":"4.8"}]
#row5 = ['5', 'True', {"lon":"2.7", "lat":"4.9"}]

df.loc[0] = row1 
df.loc[1] = row2
df.loc[2] = row3 
#df.loc[3] = row4 
#df.loc[4] = row5 


json_data = {'id':'1', 'tc_id':'True', 'coord':'x'}

df.to_csv('/home/ricardo/anaconda/sample.csv', sep=',', header = 0, index = 0)
#dicionario = df.to_dict
#json_data = df.to_json


import json
with open('data.json', 'w') as outfile:
    json.dump(json_data, outfile)

In [70]:
import os
os.system('bq load --source_format=NEWLINE_DELIMITED_JSON dataset.teste /home/ricardo/anaconda/teste.json /home/ricardo/anaconda/teste_schema.json')

32512

In [79]:
df

  id tc_id coord_lon coord_lat
0  1  True       2.3       4.5
1  2  True       2.3       4.5
2  3  True       2.3       4.5

In [45]:
dicionario

<bound method DataFrame.to_dict of   id  tc_id                             coord
0  1   True  {u'lat': u'4.5', u'lon': u'2.3'}
1  2   True  {u'lat': u'4.6', u'lon': u'2.4'}
2  3   True  {u'lat': u'4.7', u'lon': u'2.5'}
3  4  False  {u'lat': u'4.8', u'lon': u'2.6'}
4  5   True  {u'lat': u'4.9', u'lon': u'2.7'}>

In [47]:
json

<bound method DataFrame.to_json of   id  tc_id                             coord
0  1   True  {u'lat': u'4.5', u'lon': u'2.3'}
1  2   True  {u'lat': u'4.6', u'lon': u'2.4'}
2  3   True  {u'lat': u'4.7', u'lon': u'2.5'}
3  4  False  {u'lat': u'4.8', u'lon': u'2.6'}
4  5   True  {u'lat': u'4.9', u'lon': u'2.7'}>

In [68]:
json_data

{'coord': 'x', 'id': '1', 'tc_id': 'True'}